"use client";
import { useMemo,useState } from "react";
import { BookOpenText,Plus,Save,Search,Trash2 } from "lucide-react";
import type { Workspace } from "@/types/domain";

type Category={id:string;name:string;slug:string;position:number};
type Article={id:string;workspace_id:string;category_id:string|null;title:string;slug:string;body_html:string;excerpt:string|null;published_at:string|null;updated_at:string;kb_categories?:{name:string}|{name:string}[]|null};
export function KnowledgeWorkspace({workspace,initialArticles,initialCategories}:{workspace:Workspace;initialArticles:Article[];initialCategories:Category[]}){
 const [articles,setArticles]=useState(initialArticles);const [categories,setCategories]=useState(initialCategories);const [selectedId,setSelectedId]=useState(initialArticles[0]?.id??"");const [query,setQuery]=useState("");
 const selected=articles.find(a=>a.id===selectedId);const filtered=useMemo(()=>articles.filter(a=>a.title.toLowerCase().includes(query.toLowerCase())),[articles,query]);
 function createDraft(){const id=crypto.randomUUID();setArticles(v=>[{id,workspace_id:workspace.id,category_id:categories[0]?.id??null,title:"Untitled article",slug:`article-${Date.now()}`,body_html:"",excerpt:null,published_at:null,updated_at:new Date().toISOString()},...v]);setSelectedId(id)}
 async function save(publish=false){if(!selected)return;const response=await fetch("/api/knowledge/articles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...selected,workspaceId:workspace.id,published:publish})});const json=await response.json();if(response.ok)setArticles(v=>v.map(a=>a.id===selected.id?json.article:a));}
 async function remove(){if(!selected)return;await fetch(`/api/knowledge/articles?id=${selected.id}&workspaceId=${workspace.id}`,{method:"DELETE"});setArticles(v=>v.filter(a=>a.id!==selected.id));setSelectedId("")}
 return <section className="knowledge-page"><div className="page-title-row"><div><p className="eyebrow">{workspace.name}</p><h1>Knowledge base</h1></div><button className="primary-button" onClick={createDraft}><Plus size={16}/>New article</button></div><div className="knowledge-grid"><aside className="article-list"><div className="pane-header"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search articles"/></label></div>{filtered.map(article=><button className={`article-item ${selected?.id===article.id?"active":""}`} key={article.id} onClick={()=>setSelectedId(article.id)}><strong>{article.title}</strong><div className="muted">{article.published_at?"Published":"Draft"}</div></button>)}</aside><main className="editor">{selected?<><label>Title<input value={selected.title} onChange={e=>setArticles(v=>v.map(a=>a.id===selected.id?{...a,title:e.target.value}:a))}/></label><label>Category<select value={selected.category_id??""} onChange={e=>setArticles(v=>v.map(a=>a.id===selected.id?{...a,category_id:e.target.value||null}:a))}><option value="">Uncategorised</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Article body<textarea value={selected.body_html} onChange={e=>setArticles(v=>v.map(a=>a.id===selected.id?{...a,body_html:e.target.value}:a))} placeholder="Write a clear customer-facing answer…"/></label><div className="filters"><button className="primary-button" onClick={()=>save(false)}><Save size={15}/>Save draft</button><button className="chip" onClick={()=>save(true)}><BookOpenText size={15}/>Publish</button><button className="chip" onClick={remove}><Trash2 size={15}/>Delete</button></div></>:<div className="empty-state">Create or select an article.</div>}</main></div></section>;
}
