"use client";

import { useMemo, useRef, useState } from "react";
import { Bold, BookOpenText, Heading2, Italic, Link2, List, Plus, Save, Search, Trash2 } from "lucide-react";
import type { Workspace } from "@/types/domain";

type Category={id:string;name:string;slug:string;position:number};
type Article={id:string;workspace_id:string;category_id:string|null;title:string;slug:string;body_html:string;excerpt:string|null;published_at:string|null;updated_at:string;kb_categories?:{name:string}|{name:string}[]|null};

export function KnowledgeWorkspace({workspace,initialArticles,initialCategories}:{workspace:Workspace;initialArticles:Article[];initialCategories:Category[]}){
 const [articles,setArticles]=useState(initialArticles);const [categories]=useState(initialCategories);const [selectedId,setSelectedId]=useState(initialArticles[0]?.id??"");const [query,setQuery]=useState("");const [notice,setNotice]=useState("");const bodyRef=useRef<HTMLTextAreaElement|null>(null);
 const selected=articles.find(a=>a.id===selectedId);const filtered=useMemo(()=>articles.filter(a=>`${a.title} ${a.excerpt??""}`.toLowerCase().includes(query.toLowerCase())),[articles,query]);
 const patch=(changes:Partial<Article>)=>selected&&setArticles(v=>v.map(a=>a.id===selected.id?{...a,...changes}:a));
 function createDraft(){const id=`draft-${crypto.randomUUID()}`;setArticles(v=>[{id,workspace_id:workspace.id,category_id:categories[0]?.id??null,title:"Untitled article",slug:`article-${Date.now()}`,body_html:"",excerpt:null,published_at:null,updated_at:new Date().toISOString()},...v]);setSelectedId(id);setNotice("")}
 function wrap(before:string,after=before,placeholder="text"){
  if(!selected)return;const area=bodyRef.current;const start=area?.selectionStart??selected.body_html.length;const end=area?.selectionEnd??start;const chosen=selected.body_html.slice(start,end)||placeholder;const value=`${selected.body_html.slice(0,start)}${before}${chosen}${after}${selected.body_html.slice(end)}`;patch({body_html:value});requestAnimationFrame(()=>{area?.focus();area?.setSelectionRange(start+before.length,start+before.length+chosen.length)});
 }
 function addLink(){const url=window.prompt("Link URL","https://");if(url?.startsWith("http"))wrap(`<a href="${url}" target="_blank" rel="noreferrer">`,`</a>`,"link text")}
 async function save(publish=false){
  if(!selected)return;setNotice("Saving…");const isDraft=selected.id.startsWith("draft-");
  const response=await fetch("/api/knowledge/articles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:isDraft?undefined:selected.id,workspaceId:workspace.id,categoryId:selected.category_id,title:selected.title,slug:selected.slug,excerpt:selected.excerpt,bodyHtml:selected.body_html,published:publish})});
  const json=await response.json();if(response.ok){setArticles(v=>v.map(a=>a.id===selected.id?json.article:a));setSelectedId(json.article.id);setNotice(publish?"Article published":"Draft saved")}else setNotice(json.error??"Could not save article");
 }
 async function remove(){if(!selected)return;if(!selected.id.startsWith("draft-")){const response=await fetch(`/api/knowledge/articles?id=${selected.id}&workspaceId=${workspace.id}`,{method:"DELETE"});if(!response.ok){setNotice("Could not delete article");return}}setArticles(v=>v.filter(a=>a.id!==selected.id));setSelectedId("");setNotice("Article deleted")}
 return <section className="knowledge-page"><div className="page-title-row"><div><p className="eyebrow">{workspace.name}</p><h1>Knowledge base</h1></div><button className="primary-button" onClick={createDraft}><Plus size={16}/>New article</button></div>{notice&&<div className="section-card">{notice}</div>}<div className="knowledge-grid"><aside className="article-list"><div className="pane-header"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search articles"/></label></div>{filtered.map(article=><button className={`article-item ${selected?.id===article.id?"active":""}`} key={article.id} onClick={()=>setSelectedId(article.id)}><strong>{article.title}</strong><div className="muted">{article.published_at?"Published":"Draft"}</div></button>)}</aside><main className="editor">{selected?<><label>Title<input value={selected.title} onChange={e=>patch({title:e.target.value})}/></label><label>Slug<input value={selected.slug} onChange={e=>patch({slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,"-")})}/></label><label>Excerpt<textarea value={selected.excerpt??""} onChange={e=>patch({excerpt:e.target.value||null})} placeholder="Short description used in search results"/></label><label>Category<select value={selected.category_id??""} onChange={e=>patch({category_id:e.target.value||null})}><option value="">Uncategorised</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="filters" aria-label="Rich text controls"><button type="button" className="chip" onClick={()=>wrap("<strong>","</strong>")}><Bold size={14}/>Bold</button><button type="button" className="chip" onClick={()=>wrap("<em>","</em>")}><Italic size={14}/>Italic</button><button type="button" className="chip" onClick={()=>wrap("<h2>","</h2>","Heading")}><Heading2 size={14}/>Heading</button><button type="button" className="chip" onClick={()=>wrap("<ul><li>","</li></ul>","List item")}><List size={14}/>List</button><button type="button" className="chip" onClick={addLink}><Link2 size={14}/>Link</button></div><label>Article body<textarea ref={bodyRef} value={selected.body_html} onChange={e=>patch({body_html:e.target.value})} placeholder="Write a clear customer-facing answer…" rows={16}/></label><div className="filters"><button className="primary-button" onClick={()=>void save(false)}><Save size={15}/>Save draft</button><button className="chip" onClick={()=>void save(true)}><BookOpenText size={15}/>Publish</button><button className="chip" onClick={()=>void remove()}><Trash2 size={15}/>Delete</button></div></>:<div className="empty-state">Create or select an article.</div>}</main></div></section>;
}
