import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { deliverWebhook } from "@/lib/webhook-delivery";

async function adminContext(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return {error:Response.json({error:"Unauthorized"},{status:401})} as const;const {data:membership}=await db.from("memberships").select("workspace_id,role").eq("user_id",user.id).eq("role","admin").limit(1).maybeSingle();if(!membership)return {error:Response.json({error:"Admin access required"},{status:403})} as const;return {db,membership} as const;}

export async function GET(request:Request){const context=await adminContext();if("error" in context)return context.error;const url=new URL(request.url);const webhookId=url.searchParams.get("webhookId");let query=context.db.from("webhook_deliveries").select("id,webhook_id,event,status,response_status,attempts,last_error,created_at,delivered_at,next_attempt_at,response_body,outbound_webhooks!inner(workspace_id,url)").eq("outbound_webhooks.workspace_id",context.membership.workspace_id).order("created_at",{ascending:false}).limit(100);if(webhookId)query=query.eq("webhook_id",webhookId);const {data,error}=await query;if(error)return Response.json({error:error.message},{status:500});return Response.json({deliveries:data??[]},{headers:{"cache-control":"no-store"}});}

const retrySchema=z.object({deliveryId:z.string().uuid()});
export async function POST(request:Request){const parsed=retrySchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Invalid delivery"},{status:400});const context=await adminContext();if("error" in context)return context.error;const {data,error}=await context.db.from("webhook_deliveries").select("id,event,payload,attempts,outbound_webhooks!inner(id,url,secret,workspace_id)").eq("id",parsed.data.deliveryId).eq("outbound_webhooks.workspace_id",context.membership.workspace_id).maybeSingle();if(error)return Response.json({error:error.message},{status:500});if(!data)return Response.json({error:"Delivery not found"},{status:404});const hook=Array.isArray(data.outbound_webhooks)?data.outbound_webhooks[0]:data.outbound_webhooks;if(!hook)return Response.json({error:"Webhook not found"},{status:404});const result=await deliverWebhook({id:hook.id,url:hook.url,secret:hook.secret},{id:data.id,event:data.event,payload:data.payload as Record<string,unknown>,attempts:data.attempts});return Response.json({result},{status:result.ok?200:502});}
