"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, MessageSquareText, Sparkles, Users } from "lucide-react";

export default function OnboardingPage() {
  const router = useRouter(); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const response=await fetch("/api/workspaces/bootstrap",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,slug})});const json=await response.json();setBusy(false);if(!response.ok){setError(json.error??"Could not create workspace");return;}router.push("/inbox");router.refresh();}
  return <main className="onboarding-page"><section className="onboarding-copy"><span className="brand-mark"><MessageSquareText size={20}/></span><p className="eyebrow">Welcome to RelayDesk</p><h1>One place to support every customer.</h1><p>Set up your workspace, install the messenger, and bring live chat, email, knowledge and AI assistance into one focused inbox.</p><div className="onboarding-points"><span><Check size={16}/> Realtime website messenger</span><span><Users size={16}/> Admin and agent collaboration</span><span><Sparkles size={16}/> AI summaries and article suggestions</span></div></section><form className="onboarding-card" onSubmit={submit}><span className="step-label">Step 1 of 3</span><h2>Create your workspace</h2><p className="muted">This is the support space your team will share.</p><label>Workspace name<input value={name} onChange={e=>{setName(e.target.value);if(!slug)setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}} placeholder="Acme Support" required/></label><label>Workspace URL<div className="slug-field"><span>relaydesk.app/</span><input value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} placeholder="acme" required/></div></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy?"Creating…":"Create workspace"}<ArrowRight size={16}/></button></form></main>;
}
