export function DashboardUiPolish(){return <style jsx global>{`
  :root{--ui-bg:#f6f6f3;--ui-surface:#fff;--ui-border:#e2e2dc;--ui-border-strong:#d3d3cc;--ui-text:#171717;--ui-muted:#71716c;--ui-radius-sm:10px;--ui-radius-md:14px;--ui-radius-lg:18px;--ui-shadow:0 10px 30px rgba(20,20,20,.05)}
  .dashboard-content{background:var(--ui-bg)!important}
  .dashboard-content,.dashboard-content *{box-sizing:border-box}
  .dashboard-content button,.dashboard-content select,.dashboard-content input,.dashboard-content textarea{transition:border-color .15s ease,box-shadow .15s ease,background .15s ease,transform .15s ease}
  .dashboard-content button:focus-visible,.dashboard-content select:focus-visible,.dashboard-content input:focus-visible,.dashboard-content textarea:focus-visible{outline:3px solid rgba(79,124,255,.16)!important;outline-offset:1px!important;border-color:#8da7ff!important}
  .dashboard-content button:not(:disabled):hover{transform:translateY(-1px)}
  .button,.primary-button,.btn,.chip{min-height:38px!important;padding:8px 13px!important;border-radius:10px!important;font-size:14px!important;font-weight:750!important;line-height:1!important}
  .primary-button,.btn,.primary{background:#171717!important;color:#fff!important;border:1px solid #171717!important;box-shadow:0 3px 10px rgba(0,0,0,.12)!important}
  .secondary,.chip{background:#fff!important;color:#272724!important;border:1px solid var(--ui-border-strong)!important;box-shadow:0 1px 2px rgba(0,0,0,.025)!important}
  .chip.active{background:#171717!important;color:#fff!important;border-color:#171717!important}
  .dashboard-content input,.dashboard-content textarea,.dashboard-content select{min-height:40px!important;border:1px solid var(--ui-border-strong)!important;border-radius:10px!important;background:#fff!important;color:var(--ui-text)!important;padding:9px 11px!important}
  .dashboard-content textarea{line-height:1.5!important}
  .knowledge-page,.settings-page{width:min(1320px,100%)!important;padding:30px clamp(20px,3vw,40px)!important}
  .page-title-row{align-items:flex-end!important;margin-bottom:20px!important}
  .page-title-row h1,.knowledge-page h1,.settings-page h1{margin:0!important;font-size:clamp(32px,3vw,44px)!important;line-height:1!important;letter-spacing:-.04em!important}
  .page-title-row .eyebrow{margin:0 0 5px!important;font-size:13px!important;line-height:1.2!important;letter-spacing:.09em!important}
  .page-title-row p,.knowledge-page>p,.settings-page>p{color:var(--ui-muted)!important;line-height:1.5!important}
  .panel,.section-card,.article-list,.editor{border:1px solid var(--ui-border)!important;border-radius:16px!important;background:var(--ui-surface)!important;box-shadow:var(--ui-shadow)!important}
  .settings-grid{gap:16px!important;align-items:start!important}.settings-grid>.panel,.settings-grid>.section-card{padding:20px!important}
  .settings-grid h3{font-size:20px!important;line-height:1.2!important}
  .knowledge-grid{gap:18px!important}.article-list{overflow:hidden!important}.article-item{padding:14px 16px!important}.article-item.active{background:#f0f2ff!important;box-shadow:inset 3px 0 0 #5f7cff!important}
  .article-list .pane-header label{position:relative!important;display:block!important;margin:0!important}.article-list .pane-header label>svg{position:absolute!important;left:14px!important;top:50%!important;transform:translateY(-50%)!important;z-index:1!important;pointer-events:none!important;color:#6b7280!important}.article-list .pane-header input{width:100%!important;padding-left:42px!important}
  .editor{padding:20px!important}.editor input,.editor textarea,.editor select{margin-bottom:12px!important}
  .workspace-page{background:var(--ui-bg)!important;grid-template-columns:minmax(280px,330px) minmax(0,1fr) minmax(240px,280px)!important}
  .conversation-list,.conversation-view,.context-panel{background:var(--ui-surface)!important}
  .conversation-list{border-right:1px solid var(--ui-border)!important}
  .pane-header{padding:18px 18px 15px!important;border-bottom:1px solid var(--ui-border)!important}
  .pane-header h1{font-size:28px!important;line-height:1!important;letter-spacing:-.035em!important}
  .pane-header .filters{gap:7px!important;margin-top:10px!important}.pane-header label{margin-top:10px!important}
  .conversation-row{padding:13px 15px!important;border-bottom:1px solid #ecece7!important}.conversation-row:hover{background:#fafaf8!important}.conversation-row.active{background:#f0f2ff!important;box-shadow:inset 3px 0 0 #5f7cff!important}
  .conversation-header{min-height:68px!important;padding:12px 16px!important;border-bottom:1px solid var(--ui-border)!important;gap:10px!important}.conversation-header .filters{gap:7px!important}.conversation-header select{min-width:110px!important;max-width:160px!important}
  .messages{padding:18px!important;gap:10px!important;background:linear-gradient(180deg,#f8f8f5 0%,#f3f3ef 100%)!important}.message{border-radius:14px!important;border-color:var(--ui-border)!important;box-shadow:0 3px 12px rgba(0,0,0,.035)!important}
  .composer{padding:12px 14px!important;border-top:1px solid var(--ui-border)!important;box-shadow:0 -8px 24px rgba(20,20,20,.035)!important}.composer textarea{min-height:82px!important;padding:10px!important;border:1px solid var(--ui-border-strong)!important;border-radius:11px!important}
  .context-panel{padding:16px!important}.context-panel .section-card{padding:14px!important;margin-bottom:10px!important;box-shadow:none!important}.empty-state,.empty-list{color:var(--ui-muted)!important}.empty-list{padding:24px 20px!important}

  .inbox-shell{height:100svh!important;max-height:100svh!important;min-height:0!important;grid-template-columns:minmax(280px,30vw) minmax(440px,1fr) minmax(220px,260px)!important;overflow:hidden!important}
  .inbox-rail,.thread-pane,.customer-pane{height:100%!important;max-height:100%!important;min-height:0!important;overflow:hidden!important}.inbox-rail{display:flex!important;flex-direction:column!important}
  .rail-head{padding:18px 20px 10px!important;flex:0 0 auto!important}.rail-head h1{font-size:clamp(30px,2.6vw,40px)!important;line-height:1!important}.status-tabs,.search-box,.filter-row,.select-field{flex:0 0 auto!important}
  .conversation-scroll{flex:1 1 auto!important;min-height:0!important;overflow-y:auto!important;overscroll-behavior:contain!important;padding-bottom:18px!important;scrollbar-gutter:stable!important}.conversation-card{min-height:82px!important;padding:12px 15px!important}
  .thread-pane{display:grid!important;grid-template-rows:max-content max-content minmax(0,1fr) max-content!important;min-height:0!important;overflow:hidden!important}.thread-head{min-height:0!important;padding:11px 15px!important;gap:10px!important;align-items:center!important}.thread-identity h2{font-size:21px!important}.thread-identity p{font-size:13px!important}
  .thread-actions{display:flex!important;flex-wrap:wrap!important;justify-content:flex-end!important;gap:7px!important}.thread-actions label{min-width:155px!important}.thread-actions select,.thread-actions button{min-height:38px!important}
  .message-scroll{height:auto!important;max-height:none!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior:contain!important;scrollbar-gutter:stable!important;padding:18px 22px!important}.message-stack{min-height:0!important;height:max-content!important;padding-bottom:8px!important}
  .composer-card{position:relative!important;z-index:3!important;align-self:end!important;display:grid!important;grid-template-rows:max-content minmax(64px,96px) max-content!important;min-height:0!important;max-height:none!important;overflow:hidden!important;margin:0 12px 10px!important;background:#fff!important;box-shadow:0 -10px 28px rgba(20,20,20,.06)!important}.composer-card textarea{width:100%!important;height:100%!important;min-height:64px!important;max-height:96px!important;resize:none!important;overflow-y:auto!important}.composer-top,.composer-bottom{padding:9px 11px!important;flex:0 0 auto!important}.composer-bottom{min-height:52px!important;display:flex!important;align-items:center!important}.send-button{flex:0 0 auto!important}.customer-pane{overflow-y:auto!important;overscroll-behavior:contain!important}

  @media(max-height:760px) and (min-width:761px){.rail-head{padding-top:12px!important}.status-tabs{margin-top:6px!important}.search-box{margin-top:8px!important}.filter-row{margin-top:8px!important}.select-field{margin-top:8px!important}.thread-head{padding-block:8px!important}.message-scroll{padding:12px 16px!important}.composer-card{grid-template-rows:max-content minmax(54px,72px) max-content!important;margin-bottom:8px!important}.composer-card textarea{min-height:54px!important;max-height:72px!important}.composer-top,.composer-bottom{padding:7px 10px!important}.composer-bottom{min-height:46px!important}}
  @media(max-width:1450px){.workspace-page{grid-template-columns:minmax(280px,330px) minmax(0,1fr)!important}.context-panel{display:none!important}.inbox-shell{grid-template-columns:minmax(270px,320px) minmax(0,1fr)!important}.customer-pane{display:none!important}}
  @media(max-width:1200px){.settings-grid{grid-template-columns:1fr!important}.knowledge-page,.settings-page{width:min(920px,100%)!important}.inbox-shell{grid-template-columns:minmax(255px,295px) minmax(0,1fr)!important}.thread-head{align-items:flex-start!important}.thread-actions{width:100%!important;justify-content:flex-start!important}.thread-actions label{min-width:145px!important;flex:1 1 160px!important}.composer-card{margin:0 9px 8px!important}.message-scroll{padding:14px!important}}
  @media(max-width:980px){.knowledge-page,.settings-page{padding:24px 18px!important}.page-title-row h1,.knowledge-page h1,.settings-page h1{font-size:34px!important}.workspace-page{grid-template-columns:minmax(260px,300px) minmax(0,1fr)!important}.conversation-header{align-items:flex-start!important;flex-direction:column!important}.conversation-header .filters{width:100%!important;justify-content:flex-start!important}.inbox-shell{grid-template-columns:minmax(235px,275px) minmax(0,1fr)!important}.rail-head{padding-inline:16px!important}.conversation-card{padding-inline:12px!important}.thread-head{padding:10px 12px!important}.thread-identity h2{font-size:19px!important}}
  @media(max-width:760px){.knowledge-page,.settings-page{padding:20px 12px 94px!important}.page-title-row{align-items:flex-start!important;gap:12px!important;flex-direction:column!important}.page-title-row h1,.knowledge-page h1,.settings-page h1{font-size:31px!important}.workspace-page{display:block!important;min-height:calc(100svh - 82px)!important}.conversation-list{min-height:calc(100svh - 82px)!important;max-height:none!important;border-right:0!important}.conversation-view{display:none!important}.pane-header{padding:16px 14px!important}.pane-header h1{font-size:26px!important}.pane-header .filters{overflow-x:auto!important;flex-wrap:nowrap!important;padding-bottom:2px!important}.pane-header .filters>*{flex:none!important}.button,.primary-button,.btn,.chip{min-height:36px!important;padding:7px 11px!important}.inbox-shell{display:block!important;height:calc(100svh - 82px)!important;max-height:calc(100svh - 82px)!important;overflow:hidden!important}.inbox-rail{height:100%!important}.conversation-scroll{padding-bottom:100px!important}.thread-pane{display:none!important}}
`}</style>}
