import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

const mutationSchema=z.object({workspaceId:z.string().uuid(),membershipId:z.string().uuid(),role:z.enum(["admin","agent"]).optional(),action:z.enum(["update","remove"])});
async function context(workspaceId:string){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return{error:NextResponse.json({error:"Unauthorized"},{status:401})};const {data:membership}=await db.from("memberships").select("id,workspace_id,role").eq("user_id",user.id).eq("workspace_id",workspaceId).maybeSingle();if(!membership)return{error:NextResponse.json({error:"You do not have access to this workspace."},{status:403})};return{db,user,membership};}
export async function GET(request:Request){const workspaceId=new URL(request.url).searchParams.get("workspaceId");if(!workspaceId||!z.string().uuid().safeParse(workspaceId).success)return NextResponse.json({error:"Invalid workspace."},{status:400});const ctx=await context(workspaceId);if("error"in ctx)return ctx.error;const {db,membership}=ctx;const {data:members,error}=await db.from("memberships").select("id,user_id,role,created_at").eq("workspace_id",workspaceId).order("created_at");if(error)return NextResponse.json({error:error.message},{status:500});const admin=createAdminClient();const enriched=await Promise.all((members??[]).map(async member=>{const {data}=await admin.auth.admin.getUserById(member.user_id);return{...member,email:data.user?.email??null,name:data.user?.user_metadata?.full_name??data.user?.user_metadata?.name??null,status:"active" as const};}));const {data:invitations,error:invitationError}=await db.from("invitations").select("id,email,role,expires_at,accepted_at,created_at").eq("workspace_id",workspaceId).order("created_at",{ascending:false}).limit(50);if(invitationError)return NextResponse.json({error:invitationError.message},{status:500});const now=Date.now();return NextResponse.json({members:enriched,invitations:(invitations??[]).map(i=>({...i,status:i.accepted_at?"accepted":new Date(i.expires_at).getTime()<=now?"expired":"pending"})),currentMembershipId:membership.id});}
export async function PATCH(request:Request){const parsed=mutationSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid team change."},{status:400});const ctx=await context(parsed.data.workspaceId);if("error"in ctx)return ctx.error;const {db,membership}=ctx;if(membership.role!=="admin")return NextResponse.json({error:"Only admins can manage this team."},{status:403});const {data:target}=await db.from("memberships").select("id,workspace_id,role").eq("id",parsed.data.membershipId).eq("workspace_id",parsed.data.workspaceId).maybeSingle();if(!target)return NextResponse.json({error:"Team member not found in this workspace."},{status:404});if(target.id===membership.id)return NextResponse.json({error:"Use Leave workspace for your own membership. You cannot change or remove yourself here."},{status:403});const {count:adminCount}=await db.from("memberships").select("id",{count:"exact",head:true}).eq("workspace_id",parsed.data.workspaceId).eq("role","admin");if(target.role==="admin"&&(adminCount??0)<=1&&(parsed.data.action==="remove"||parsed.data.role==="agent"))return NextResponse.json({error:"Promote another admin before changing or removing the last admin."},{status:400});if(parsed.data.action==="remove"){const {error}=await db.from("memberships").delete().eq("id",target.id).eq("workspace_id",parsed.data.workspaceId);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true});}if(!parsed.data.role)return NextResponse.json({error:"Choose a role."},{status:400});if(target.role===parsed.data.role)return NextResponse.json({member:{id:target.id,role:target.role},unchanged:true});const {data:updated,error}=await db.from("memberships").update({role:parsed.data.role}).eq("id",target.id).eq("workspace_id",parsed.data.workspaceId).select("id,role").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({member:updated});}
