"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Building2, Check, Plus, UserPlus } from "lucide-react";

type WorkspaceItem={id:string;name:string;slug:string;role:"admin"|"agent"};
type Invite={id:string;workspaceName:string;role:"admin"|"agent";expiresAt:string};

export function WorkspaceHub(){
 const [workspaces,setWorkspaces]=useState<WorkspaceItem[]>([]);const [activeId,setActiveId]=useState<string|null>(null);const [invites,setInvites]=useState<Invite[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const [contextResponse,inviteResponse]=await Promise.all([fetch("/api/workspaces/context",{cache:"no-store"}),fetch("/api/team/pending",{cache:"no-store"})]);const context=await contextResponse.json();const inviteJson=await inviteResponse.json();if(!contextResponse.ok)throw new Error(context.error??"Could not load workspaces");setWorkspaces(context.workspaces??[]);setActiveId(context.activeWorkspaceId??null);if(inviteResponse.ok)setInvites(inviteJson.invitations??[])}catch(caught){setError(caught instanceof Error?caught.message:"Could not load workspaces")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function openWorkspace(workspaceId:string){setLoading(true);const response=await fetch("/api/workspaces/context",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId})});const json=await response.json().catch(()=>({}));if(!response.ok){setError(json.error??"Could not switch workspace");setLoading(false);return}window.location.assign("/inbox")}
 async function handleInvite(invitationId:string,action:"accept"|"decline"){setLoading(true);setError("");const response=await fetch("/api/team/pending",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invitationId,action})});const json=await response.json().catch(()=>({}));if(!response.ok){setError(json.error??`Could not ${action} invitation`);setLoading(false);return}if(action==="accept"){await openWorkspace(json.workspaceId);return}setInvites(current=>current.filter(invite=>invite.id!==invitationId));setLoading(false)}
 return <section className="workspace-hub"><div className="hub-head"><div><p className="eyebrow">RelayDesk</p><h1>Workspaces</h1><p className="muted">Open a workspace, handle invitations, or create a new one.</p></div><Link href="/onboarding" className="primary-button"><Plus size={16}/>Create workspace</Link></div>{error?<p className="form-error">{error}</p>:null}{loading?<p className="muted">Updating workspaces…</p>:null}<div className="hub-grid"><div className="section-card"><h2><Building2 size={18}/>Your workspaces</h2><div className="workspace-list">{workspaces.map(workspace=><button key={workspace.id} className={`workspace-row ${workspace.id===activeId?"active":""}`} disabled={loading} onClick={()=>openWorkspace(workspace.id)}><span><strong>{workspace.name}</strong><small>{workspace.role} · {workspace.slug}</small></span>{workspace.id===activeId?<span className="current"><Check size={14}/>Current</span>:<span>Open</span>}</button>)}</div>{!workspaces.length&&!loading?<p className="muted">No workspaces yet.</p>:null}</div><div className="section-card"><h2><UserPlus size={18}/>Pending invitations</h2>{invites.length?<div className="invite-list">{invites.map(invite=><div className="invite-row" key={invite.id}><span><strong>{invite.workspaceName}</strong><small>{invite.role} access · expires {new Date(invite.expiresAt).toLocaleDateString()}</small></span><div><button className="primary-button" disabled={loading} onClick={()=>handleInvite(invite.id,"accept")}>Accept</button><button className="chip" disabled={loading} onClick={()=>handleInvite(invite.id,"decline")}>Decline</button></div></div>)}</div>:<p className="muted">No pending invitations.</p>}</div></div><style jsx>{`.workspace-hub{padding:42px;max-width:1180px;margin:0 auto}.hub-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:24px}.hub-head h1{margin:4px 0 8px;font-size:52px}.hub-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:20px}.section-card h2{display:flex;align-items:center;gap:8px}.workspace-list,.invite-list{display:grid;gap:10px}.workspace-row{width:100%;display:flex;justify-content:space-between;align-items:center;text-align:left;padding:16px;border:1px solid #ddd;border-radius:14px;background:#fff}.workspace-row.active{border-color:#171717;background:#f5f5f1}.workspace-row span:first-child,.invite-row>span{display:grid;gap:4px}.workspace-row small,.invite-row small{color:#707070}.current{display:flex;align-items:center;gap:5px;font-weight:800}.invite-row{display:grid;gap:12px;padding:14px 0;border-top:1px solid #eee}.invite-row>div{display:flex;gap:8px}@media(max-width:820px){.workspace-hub{padding:24px 18px}.hub-head{flex-direction:column}.hub-head h1{font-size:40px}.hub-grid{grid-template-columns:1fr}}`}</style></section>
}
