"use client";

import { useEffect, useState } from "react";
import { Copy, KeyRound, ShieldCheck, Trash2 } from "lucide-react";

type ApiKey = { id:string; name:string; key_prefix:string; scopes:string[]; last_used_at:string|null; expires_at:string|null; revoked_at:string|null; created_at:string };
type Policy = { first_response_minutes:number; resolution_minutes:number; warning_minutes:number; enabled:boolean };
const scopeOptions = ["conversations:read","conversations:write","contacts:read","messages:read"];

export function ApiAccessManager({isAdmin}:{isAdmin:boolean}){
 const [keys,setKeys]=useState<ApiKey[]>([]);const [name,setName]=useState("Production integration");const [scopes,setScopes]=useState<string[]>(["conversations:read"]);const [secret,setSecret]=useState("");const [policy,setPolicy]=useState<Policy>({first_response_minutes:60,resolution_minutes:1440,warning_minutes:15,enabled:true});const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 async function load(){if(!isAdmin)return;const [keysResponse,slaResponse]=await Promise.all([fetch("/api/api-keys",{cache:"no-store"}),fetch("/api/sla",{cache:"no-store"})]);const keysJson=await keysResponse.json();const slaJson=await slaResponse.json();if(keysResponse.ok)setKeys(keysJson.apiKeys??[]);if(slaResponse.ok&&slaJson.policy)setPolicy(slaJson.policy);}
 useEffect(()=>{void load()},[isAdmin]);
 async function createKey(){if(!name.trim()||!scopes.length||busy)return;setBusy(true);setSecret("");setNotice("");try{const response=await fetch("/api/api-keys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),scopes,expiresInDays:null})});const json=await response.json();if(response.ok){setKeys(current=>[json.apiKey,...current]);setSecret(json.secret);setNotice("API key created. Copy it now; the secret is never stored in plaintext.")}else setNotice(json.error??"Could not create API key")}catch{setNotice("Could not reach the server")}finally{setBusy(false)}}
 async function revoke(id:string){if(busy||!window.confirm("Revoke this API key immediately?"))return;setBusy(true);const response=await fetch("/api/api-keys",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({keyId:id})});const json=await response.json();if(response.ok)setKeys(current=>current.map(item=>item.id===id?{...item,revoked_at:new Date().toISOString()}:item));else setNotice(json.error??"Could not revoke API key");setBusy(false)}
 async function savePolicy(){if(busy)return;setBusy(true);const response=await fetch("/api/sla",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({firstResponseMinutes:Number(policy.first_response_minutes),resolutionMinutes:Number(policy.resolution_minutes),warningMinutes:Number(policy.warning_minutes),enabled:policy.enabled})});const json=await response.json();if(response.ok){setPolicy(json.policy);setNotice("SLA policy saved. New conversations will use the updated first-response target.")}else setNotice(json.error??"Could not save SLA policy");setBusy(false)}
 if(!isAdmin)return null;
 return <><section className="section-card"><h3><KeyRound size={16}/> API access</h3><p className="muted">Issue scoped bearer keys for external integrations. Use <code>/api/v1/conversations</code>.</p><label>Key name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><div className="api-scope-grid">{scopeOptions.map(scope=><label className="scope-option" key={scope}><input type="checkbox" checked={scopes.includes(scope)} onChange={e=>setScopes(current=>e.target.checked?[...current,scope]:current.filter(item=>item!==scope))}/><span>{scope}</span></label>)}</div><button className="primary-button" disabled={busy||!name.trim()||!scopes.length} onClick={()=>void createKey()}>Create API key</button>{secret&&<div className="secret-reveal"><pre className="code-block">{secret}</pre><button className="chip" onClick={()=>void navigator.clipboard.writeText(secret)}><Copy size={14}/>Copy</button></div>}{keys.map(key=><div className="api-key-row" key={key.id}><div><strong>{key.name}</strong><p className="muted">{key.key_prefix}… · {key.scopes.join(" · ")}</p><small className="muted">{key.revoked_at?"Revoked":key.last_used_at?`Last used ${new Date(key.last_used_at).toLocaleString()}`:"Never used"}</small></div><button className="chip danger-chip" disabled={busy||Boolean(key.revoked_at)} onClick={()=>void revoke(key.id)}><Trash2 size={14}/>Revoke</button></div>)}</section><section className="section-card"><h3><ShieldCheck size={16}/> SLA policy</h3><label className="scope-option"><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy(current=>({...current,enabled:e.target.checked}))}/><span>Enable SLA tracking</span></label><div className="sla-settings-grid"><label>First response (minutes)<input type="number" min={1} max={10080} value={policy.first_response_minutes} onChange={e=>setPolicy(current=>({...current,first_response_minutes:Number(e.target.value)}))}/></label><label>Resolution target (minutes)<input type="number" min={1} max={43200} value={policy.resolution_minutes} onChange={e=>setPolicy(current=>({...current,resolution_minutes:Number(e.target.value)}))}/></label><label>Warning window (minutes)<input type="number" min={1} max={1440} value={policy.warning_minutes} onChange={e=>setPolicy(current=>({...current,warning_minutes:Number(e.target.value)}))}/></label></div><button className="primary-button" disabled={busy} onClick={()=>void savePolicy()}>Save SLA policy</button>{notice&&<p>{notice}</p>}</section></>;
}
