"use client";

import { useEffect,useState } from "react";
import { Copy,KeyRound,ShieldCheck,Trash2 } from "lucide-react";

type ApiKey={id:string;name:string;key_prefix:string;scopes:string[];last_used_at:string|null;expires_at:string|null;revoked_at:string|null;created_at:string};
type Policy={first_response_minutes:number;resolution_minutes:number;warning_minutes:number;enabled:boolean};
type Notice={tone:"success"|"error"|"info";text:string}|null;
const scopeOptions=["conversations:read","conversations:write","contacts:read","messages:read"];

export function ApiAccessManager({isAdmin}:{isAdmin:boolean}){
 const [keys,setKeys]=useState<ApiKey[]>([]);
 const [name,setName]=useState("Production integration");
 const [scopes,setScopes]=useState<string[]>(["conversations:read"]);
 const [secret,setSecret]=useState("");
 const [policy,setPolicy]=useState<Policy>({first_response_minutes:60,resolution_minutes:1440,warning_minutes:15,enabled:true});
 const [notice,setNotice]=useState<Notice>(null);
 const [action,setAction]=useState("");
 const busy=Boolean(action);

 async function load(){if(!isAdmin)return;try{const [keysResponse,slaResponse]=await Promise.all([fetch("/api/api-keys",{cache:"no-store"}),fetch("/api/sla",{cache:"no-store"})]);const keysJson=await keysResponse.json().catch(()=>({}));const slaJson=await slaResponse.json().catch(()=>({}));if(keysResponse.ok)setKeys(keysJson.apiKeys??[]);else throw new Error(keysJson.error??"Could not load API keys");if(slaResponse.ok&&slaJson.policy)setPolicy(slaJson.policy);}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Could not load API settings"});}}
 useEffect(()=>{void load()},[isAdmin]);

 async function createKey(){if(!name.trim()||!scopes.length||busy)return;setAction("create-key");setSecret("");setNotice({tone:"info",text:"Creating API key…"});try{const response=await fetch("/api/api-keys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),scopes,expiresInDays:null})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Could not create API key");setKeys(current=>[json.apiKey,...current]);setSecret(json.secret);setNotice({tone:"success",text:"API key created. Copy it now; the secret will not be shown again."});}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Could not create API key"});}finally{setAction("");}}

 async function revoke(id:string){if(busy||!window.confirm("Revoke this API key immediately?"))return;setAction(`revoke-${id}`);setNotice({tone:"info",text:"Revoking API key…"});try{const response=await fetch("/api/api-keys",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({keyId:id})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Could not revoke API key");setKeys(current=>current.map(item=>item.id===id?{...item,revoked_at:new Date().toISOString()}:item));setNotice({tone:"success",text:"API key revoked"});}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Could not revoke API key"});}finally{setAction("");}}

 async function savePolicy(){if(busy)return;setAction("save-sla");setNotice({tone:"info",text:"Saving SLA policy…"});try{const response=await fetch("/api/sla",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({firstResponseMinutes:Number(policy.first_response_minutes),resolutionMinutes:Number(policy.resolution_minutes),warningMinutes:Number(policy.warning_minutes),enabled:policy.enabled})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error??"Could not save SLA policy");setPolicy(json.policy);setNotice({tone:"success",text:"SLA policy saved. New conversations will use the updated target."});}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Could not save SLA policy"});}finally{setAction("");}}

 if(!isAdmin)return null;
 return <>
  <section className="section-card"><h3><KeyRound size={16}/>API access</h3><p className="muted">Issue scoped bearer keys for external integrations. Use <code>/api/v1/conversations</code>.</p>{notice&&<div className={notice.tone==="error"?"form-error":notice.tone==="success"?"form-success":"muted"} role="status" aria-live="polite">{notice.text}</div>}<label>Key name<input disabled={busy} value={name} onChange={event=>setName(event.target.value)} maxLength={80}/></label><div className="api-scope-grid">{scopeOptions.map(scope=><label className="scope-option" key={scope}><input disabled={busy} type="checkbox" checked={scopes.includes(scope)} onChange={event=>setScopes(current=>event.target.checked?[...current,scope]:current.filter(item=>item!==scope))}/><span>{scope}</span></label>)}</div><button className="primary-button" aria-busy={action==="create-key"} disabled={busy||!name.trim()||!scopes.length} onClick={()=>void createKey()}>{action==="create-key"?"Creating key…":"Create API key"}</button>{secret&&<div className="secret-reveal"><pre className="code-block">{secret}</pre><button className="chip" onClick={async()=>{await navigator.clipboard.writeText(secret);setNotice({tone:"success",text:"API key copied"});}}><Copy size={14}/>Copy</button></div>}{keys.map(key=><div className="api-key-row" key={key.id}><div><strong>{key.name}</strong><p className="muted">{key.key_prefix}… · {key.scopes.join(" · ")}</p><small className="muted">{key.revoked_at?"Revoked":key.last_used_at?`Last used ${new Date(key.last_used_at).toLocaleString()}`:"Never used"}</small></div><button className="chip danger-chip" aria-busy={action===`revoke-${key.id}`} disabled={busy||Boolean(key.revoked_at)} onClick={()=>void revoke(key.id)}><Trash2 size={14}/>{action===`revoke-${key.id}`?"Revoking…":"Revoke"}</button></div>)}</section>
  <section className="section-card"><h3><ShieldCheck size={16}/>SLA policy</h3><label className="scope-option"><input disabled={busy} type="checkbox" checked={policy.enabled} onChange={event=>setPolicy(current=>({...current,enabled:event.target.checked}))}/><span>Enable SLA tracking</span></label><div className="sla-settings-grid"><label>First response (minutes)<input disabled={busy} type="number" min={1} max={10080} value={policy.first_response_minutes} onChange={event=>setPolicy(current=>({...current,first_response_minutes:Number(event.target.value)}))}/></label><label>Resolution target (minutes)<input disabled={busy} type="number" min={1} max={43200} value={policy.resolution_minutes} onChange={event=>setPolicy(current=>({...current,resolution_minutes:Number(event.target.value)}))}/></label><label>Warning window (minutes)<input disabled={busy} type="number" min={1} max={1440} value={policy.warning_minutes} onChange={event=>setPolicy(current=>({...current,warning_minutes:Number(event.target.value)}))}/></label></div><button className="primary-button" aria-busy={action==="save-sla"} disabled={busy} onClick={()=>void savePolicy()}>{action==="save-sla"?"Saving policy…":"Save SLA policy"}</button></section>
 </>;
}
