"use client";
import { useState } from "react";
import { Check,Copy,Globe2,Mail,UserPlus } from "lucide-react";
import type { Membership,Workspace } from "@/types/domain";

type Domain={id:string;hostname:string;verification_token:string;status:string;verified_at:string|null};
export function SettingsWorkspace({workspace,membership,initialDomains,inboundAddress,memberCount}:{workspace:Workspace;membership:Membership;initialDomains:Domain[];inboundAddress:string|null;memberCount:number}){
 const [domains,setDomains]=useState(initialDomains);const [hostname,setHostname]=useState("");const [email,setEmail]=useState("");const [notice,setNotice]=useState("");
 const appUrl=typeof window!=="undefined"?window.location.origin:process.env.NEXT_PUBLIC_APP_URL||"https://your-app.vercel.app";
 const snippet=`<script src="${appUrl}/widget/loader.js" data-workspace="${workspace.public_key}" async></script>`;
 async function invite(){const r=await fetch("/api/team/invite",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:workspace.id,email,role:"agent"})});const j=await r.json();setNotice(r.ok?"Invitation created":j.error||"Could not invite");}
 async function addDomain(){const r=await fetch("/api/domains",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:workspace.id,hostname})});const j=await r.json();if(r.ok){setDomains(v=>[...v,j.domain]);setHostname("")}else setNotice(j.error)}
 async function verify(domain:Domain){const r=await fetch("/api/domains",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:workspace.id,domainId:domain.id})});const j=await r.json();if(r.ok)setDomains(v=>v.map(d=>d.id===domain.id?j.domain:d));else setNotice(j.error)}
 return <section className="settings-page"><div className="page-title-row"><div><p className="eyebrow">{workspace.name}</p><h1>Settings</h1></div><span className="muted">{membership.role} · {memberCount} member{memberCount===1?"":"s"}</span></div>{notice&&<div className="section-card">{notice}</div>}<div className="settings-grid"><div className="section-card"><h3><Copy size={16}/> Install messenger</h3><p className="muted">Paste this before the closing body tag on any site.</p><pre className="code-block">{snippet}</pre><button className="chip" onClick={()=>navigator.clipboard.writeText(snippet)}>Copy snippet</button></div><div className="section-card"><h3><Mail size={16}/> Email inbox</h3><p>Forward support mail to:</p><pre className="code-block">{inboundAddress||"Created automatically after workspace setup"}</pre></div><div className="section-card"><h3><UserPlus size={16}/> Invite teammate</h3><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="agent@company.com"/></label><button className="primary-button" onClick={invite}>Send invite</button></div><div className="section-card"><h3><Globe2 size={16}/> Custom help domain</h3><label>Hostname<input value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="help.company.com"/></label><button className="primary-button" onClick={addDomain}>Add domain</button>{domains.map(domain=><div key={domain.id} className="section-card"><strong>{domain.hostname}</strong><p className="muted">TXT _relaydesk.{domain.hostname} = {domain.verification_token}</p><button className="chip" onClick={()=>verify(domain)}>{domain.status==="verified"?<><Check size={14}/>Verified</>:"Verify DNS"}</button></div>)}</div></div></section>;
}
