"use client";

import { useEffect, useState } from "react";
import { PlugZap, RefreshCw, Trash2 } from "lucide-react";

type Webhook={id:string;url:string;events:string[];enabled:boolean;created_at:string;updated_at:string};
type Delivery={id:string;webhook_id:string;event:string;status:string;response_status:number|null;attempts:number;last_error:string|null;created_at:string;delivered_at:string|null;next_attempt_at:string|null};

export function WebhooksManager({isAdmin}:{isAdmin:boolean}){
 const [webhooks,setWebhooks]=useState<Webhook[]>([]);const [deliveries,setDeliveries]=useState<Delivery[]>([]);const [url,setUrl]=useState("");const [secret,setSecret]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");
 async function load(){if(!isAdmin)return;const [hooksResponse,deliveryResponse]=await Promise.all([fetch("/api/webhooks",{cache:"no-store"}),fetch("/api/webhook-deliveries",{cache:"no-store"})]);const hooksJson=await hooksResponse.json();const deliveryJson=await deliveryResponse.json();if(hooksResponse.ok)setWebhooks(hooksJson.webhooks??[]);else setNotice(hooksJson.error??"Could not load webhooks");if(deliveryResponse.ok)setDeliveries(deliveryJson.deliveries??[]);}
 useEffect(()=>{void load()},[isAdmin]);
 async function createWebhook(){if(!url.trim()||busy)return;setBusy("create");setNotice("");setSecret("");try{const response=await fetch("/api/webhooks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url:url.trim(),events:["conversation.created","message.created","conversation.updated"]})});const json=await response.json();if(response.ok){setWebhooks(current=>[json.webhook,...current]);setSecret(json.secret??"");setUrl("");setNotice("Webhook created. Copy the signing secret now; it will not be shown again.")}else setNotice(json.error??"Could not create webhook")}catch{setNotice("Could not reach the server")}finally{setBusy("")}}
 async function act(webhookId:string,action:"test"|"toggle"|"delete",enabled?:boolean){if(busy)return;setBusy(webhookId);setNotice("");const response=await fetch("/api/webhooks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({webhookId,action,enabled})});const json=await response.json();if(response.ok){if(action==="delete")setWebhooks(current=>current.filter(item=>item.id!==webhookId));else if(action==="toggle")setWebhooks(current=>current.map(item=>item.id===webhookId?json.webhook:item));else setNotice(`Test delivered successfully with HTTP ${json.status}.`);await load()}else setNotice(json.error??"Webhook action failed");setBusy("")}
 async function retry(deliveryId:string){if(busy)return;setBusy(deliveryId);setNotice("");const response=await fetch("/api/webhook-deliveries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deliveryId})});const json=await response.json();setNotice(response.ok?"Webhook delivered successfully.":json.error??json.result?.error??"Retry failed");await load();setBusy("")}
 if(!isAdmin)return null;
 return <div className="section-card webhook-manager"><h3><PlugZap size={16}/> Webhooks</h3><p className="muted">Send signed HTTPS events to your own systems. Failed attempts use exponential retry scheduling and can be retried manually.</p><label>Endpoint URL<input value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://example.com/relaydesk-webhook"/></label><button className="primary-button" disabled={Boolean(busy)||!url.trim()} onClick={()=>void createWebhook()}>{busy==="create"?"Creating…":"Add webhook"}</button>{notice&&<p>{notice}</p>}{secret&&<pre className="code-block">Signing secret: {secret}</pre>}{webhooks.map(webhook=><div className="section-card" key={webhook.id}><strong>{webhook.url}</strong><p className="muted">{webhook.events.join(" · ")} · {webhook.enabled?"enabled":"disabled"}</p><div className="filters"><button className="chip" disabled={Boolean(busy)} onClick={()=>void act(webhook.id,"test")}>Send test</button><button className="chip" disabled={Boolean(busy)} onClick={()=>void act(webhook.id,"toggle",!webhook.enabled)}>{webhook.enabled?"Disable":"Enable"}</button><button className="chip" disabled={Boolean(busy)} onClick={()=>void act(webhook.id,"delete")}><Trash2 size={14}/>Delete</button></div></div>)}<h4>Recent deliveries</h4><div className="delivery-list">{deliveries.slice(0,12).map(delivery=><div className="delivery-row" key={delivery.id}><div><strong>{delivery.event}</strong><p className="muted">{delivery.status} · {delivery.response_status??"no response"} · {delivery.attempts} attempt{delivery.attempts===1?"":"s"}</p>{delivery.last_error&&<small className="form-error">{delivery.last_error}</small>}</div>{delivery.status==="failed"&&<button className="chip" disabled={Boolean(busy)} onClick={()=>void retry(delivery.id)}><RefreshCw size={14}/>Retry</button>}</div>)}{!deliveries.length&&<p className="muted">No deliveries yet.</p>}</div></div>;
}
