"use client";
import { FormEvent,useEffect,useState } from "react";
import { MessageCircle,Send } from "lucide-react";

type Message={id:string;body:string;sender_type:"contact"|"agent"|"system";created_at:string};
export default function WidgetPage(){
 const [workspace,setWorkspace]=useState("");const [visitorToken,setVisitorToken]=useState("");const [conversationId,setConversationId]=useState("");const [messages,setMessages]=useState<Message[]>([]);const [draft,setDraft]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const key=new URLSearchParams(location.search).get("workspace")||"";setWorkspace(key);const saved=localStorage.getItem(`relaydesk:${key}`)||"";fetch("/api/widget/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceKey:key,visitorToken:saved||undefined})}).then(async r=>({ok:r.ok,json:await r.json()})).then(({ok,json})=>{if(!ok)throw new Error(json.error||"Could not connect");setVisitorToken(json.visitorToken);setConversationId(json.conversation.id);setMessages(json.messages||[]);localStorage.setItem(`relaydesk:${key}`,json.visitorToken)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!conversationId||!visitorToken)return;const timer=setInterval(async()=>{const r=await fetch(`/api/widget/messages?conversationId=${conversationId}&visitorToken=${encodeURIComponent(visitorToken)}`);if(r.ok){const j=await r.json();setMessages(j.messages||[]) }},2500);return()=>clearInterval(timer)},[conversationId,visitorToken]);
 async function send(event:FormEvent){event.preventDefault();if(!draft.trim()||busy)return;setBusy(true);const body=draft.trim();setDraft("");const r=await fetch("/api/widget/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceKey:workspace,conversationId,visitorToken,body})});const j=await r.json();if(r.ok)setMessages(v=>[...v,j.message]);else{setDraft(body);setError(j.error||"Could not send")}setBusy(false)}
 return <main className="widget-page"><section className="widget-card"><header className="widget-header"><MessageCircle size={22}/><h2>How can we help?</h2><p>We usually reply in a few minutes.</p></header><div className="widget-messages">{messages.map(message=><div className={`message ${message.sender_type==="contact"?"agent":""}`} key={message.id}>{message.body}</div>)}{!messages.length&&!error&&<div className="muted">Start a conversation with the team.</div>}{error&&<div className="form-error">{error}</div>}</div><form className="widget-form" onSubmit={send}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write a message…"/><button className="primary-button" disabled={busy||!conversationId}><Send size={15}/></button></form></section></main>;
}
