import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Pricing — Free and planned Pro",
  description: "Start free with 10,000 remote tool calls per month. Review RelayDesk pricing for compatible AI clients and paired devices.",
  alternates: { canonical: "/pricing" },
  openGraph: { title: "Pricing — Free and planned Pro | RelayDesk", description: "Start free with 10,000 remote tool calls per month. Review RelayDesk pricing for compatible AI clients and paired devices." },
};

export default function Pricing(){return <main className="shell"><div className="hero-top"><Link className="brand" href="/"><img className="brand-mark" src="/relaydesk-mark.svg" alt="" width={34} height={34} /><span>RelayDesk</span></Link><Link className="button" href="/auth/login">Sign in</Link></div><div className="eyebrow">Pricing</div><h1>Start free. Pay only when you use it heavily.</h1><p className="lead">RelayDesk keeps the remote bridge simple: your own machines, your own AI clients, and predictable remote tool-call limits.</p><div className="pricing-grid"><section className="price-card"><div className="eyebrow">Free</div><div className="price">$0 <span>/ month</span></div><p>10,000 remote tool calls per month.</p><p className="small">ChatGPT, Claude and compatible MCP clients · multiple paired devices · community support.</p><Link className="button primary" href="/auth/login">Get started</Link></section><section className="price-card"><div className="eyebrow">Pro — planned</div><div className="price">$9 <span>/ month</span></div><p>Higher remote usage for individual power users.</p><p className="small">Billing is not live yet. We will not charge until the entitlement and payment path is fully implemented and tested.</p><span className="button" aria-disabled="true">Coming soon</span></section></div><div className="links"><Link href="/">Home</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></main>}
