import { randomBytes } from "crypto";
import { promises as dns } from "dns";
import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const hostnameSchema=z.string().trim().min(4).max(253).regex(/^(?=.{1,253}$)(?!-)(?:[a-z0-9-]{1,63}\.)+[a-z]{2,63}$/i).refine(value=>value.replace(/\.$/,"").split(".").length>=3,"Use a subdomain such as help.company.com, not the root company.com domain.");
const createSchema=z.object({workspaceId:z.string().uuid(),hostname:hostnameSchema});
const domainSchema=z.object({domainId:z.string().uuid(),workspaceId:z.string().uuid()});
async function requireAdmin(db:Awaited<ReturnType<typeof createClient>>,workspaceId:string,userId:string){return db.from("memberships").select("id").eq("workspace_id",workspaceId).eq("user_id",userId).eq("role","admin").maybeSingle()}
function vercelConfig(){const token=process.env.VERCEL_TOKEN;const project=process.env.VERCEL_PROJECT_ID||process.env.VERCEL_PROJECT_NAME||"relay-desk-mjq6";const teamId=process.env.VERCEL_TEAM_ID;return token?{token,project,teamId}:null}
function projectDomainUrl(project:string,hostname?:string,action?:"verify"){const encodedProject=encodeURIComponent(project);const encodedDomain=hostname?`/${encodeURIComponent(hostname)}`:"";const suffix=action==="verify"?"/verify":"";const team=process.env.VERCEL_TEAM_ID?`?teamId=${encodeURIComponent(process.env.VERCEL_TEAM_ID)}`:"";return `https://api.vercel.com/v9/projects/${encodedProject}/domains${encodedDomain}${suffix}${team}`}
async function vercelRequest(method:"POST"|"DELETE",hostname:string,action?:"verify"){const config=vercelConfig();if(!config)return{automated:false as const,ok:false as const,message:"Owner-side Vercel automation is not configured."};const response=await fetch(projectDomainUrl(config.project,action?hostname:method==="DELETE"?hostname:undefined,action),{method,headers:{authorization:`Bearer ${config.token}`,"content-type":"application/json"},body:method==="POST"&&!action?JSON.stringify({name:hostname}):undefined,cache:"no-store"});const payload=await response.json().catch(()=>({}));const alreadyAdded=response.status===409||/already|exists/i.test(String(payload?.error?.message??payload?.message??""));if(!response.ok&&!alreadyAdded)return{automated:true as const,ok:false as const,message:String(payload?.error?.message??payload?.message??`Vercel returned ${response.status}`)};return{automated:true as const,ok:true as const,message:alreadyAdded?"Domain is already registered with RelayDesk hosting.":"Domain registered with RelayDesk hosting."}}
export async function POST(request:Request){const parsed=createSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Enter a subdomain such as help.company.com."},{status:400});const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:membership}=await requireAdmin(db,parsed.data.workspaceId,user.id);if(!membership)return NextResponse.json({error:"Only admins can add domains."},{status:403});const hostname=parsed.data.hostname.toLowerCase().replace(/\.$/,"");const token=`relaydesk-verification=${randomBytes(18).toString("hex")}`;const {data,error}=await db.from("custom_domains").insert({workspace_id:parsed.data.workspaceId,hostname,verification_token:token,status:"pending"}).select().single();if(error)return NextResponse.json({error:error.code==="23505"?"This hostname is already connected.":error.message},{status:400});const hosting=await vercelRequest("POST",hostname);return NextResponse.json({domain:data,hosting,records:{cname:{type:"CNAME",host:hostname,value:process.env.CUSTOM_DOMAIN_CNAME_TARGET??"cname.vercel-dns.com"},txt:{type:"TXT",host:`_relaydesk.${hostname}`,value:token}},message:hosting.ok?"Domain saved. Add exactly the TXT and CNAME records shown, then verify.":"Domain saved. Add exactly the TXT and CNAME records shown, then verify."})}
export async function PATCH(request:Request){const parsed=domainSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid domain."},{status:400});const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:membership}=await requireAdmin(db,parsed.data.workspaceId,user.id);if(!membership)return NextResponse.json({error:"Only admins can verify domains."},{status:403});const {data:domain}=await db.from("custom_domains").select("*").eq("id",parsed.data.domainId).eq("workspace_id",parsed.data.workspaceId).maybeSingle();if(!domain)return NextResponse.json({error:"Domain not found."},{status:404});await db.from("custom_domains").update({status:"pending",updated_at:new Date().toISOString()}).eq("id",domain.id);try{const records=(await dns.resolveTxt(`_relaydesk.${domain.hostname}`)).flat();if(!records.includes(domain.verification_token))return NextResponse.json({error:"We found the TXT record, but its value does not match. Copy the exact verification value and retry.",pending:true},{status:409});const registration=await vercelRequest("POST",domain.hostname);if(registration.automated&&!registration.ok)throw new Error(`DNS ownership passed, but hosting registration failed: ${registration.message}`);const hosting=registration.automated?await vercelRequest("POST",domain.hostname,"verify"):registration;if(hosting.automated&&!hosting.ok)throw new Error(`DNS ownership passed, but HTTPS activation is still pending: ${hosting.message}`);const {data,error}=await db.from("custom_domains").update({status:"verified",verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",domain.id).select().single();if(error)throw error;return NextResponse.json({domain:data,hosting,message:"Domain verified. HTTPS provisioning has started automatically."})}catch(error){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code??""):"";if(["ENOTFOUND","ENODATA","ETIMEOUT","EAI_AGAIN"].includes(code)){await db.from("custom_domains").update({status:"pending",updated_at:new Date().toISOString()}).eq("id",domain.id);return NextResponse.json({error:"Verification record not found yet. Add the TXT record shown, allow time for DNS propagation, then retry.",pending:true},{status:409})}const message=error instanceof Error?error.message:"Domain verification failed.";await db.from("custom_domains").update({status:"failed",updated_at:new Date().toISOString()}).eq("id",domain.id);return NextResponse.json({error:message},{status:409})}}
export async function DELETE(request:Request){const parsed=domainSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid domain."},{status:400});const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:membership}=await requireAdmin(db,parsed.data.workspaceId,user.id);if(!membership)return NextResponse.json({error:"Only admins can remove domains."},{status:403});const {data:domain}=await db.from("custom_domains").select("hostname").eq("id",parsed.data.domainId).eq("workspace_id",parsed.data.workspaceId).maybeSingle();if(!domain)return NextResponse.json({error:"Domain not found."},{status:404});const {error}=await db.from("custom_domains").delete().eq("id",parsed.data.domainId).eq("workspace_id",parsed.data.workspaceId);if(error)return NextResponse.json({error:error.message},{status:400});await vercelRequest("DELETE",domain.hostname);return NextResponse.json({ok:true})}
